[package]
name = "dsp-bridge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "_dsp_kitchen"
crate-type = ["cdylib", "rlib"]

[dependencies]
dsp-core.workspace = true
dsp-base.workspace = true
dsp-stream.workspace = true
cubecl = { workspace = true, features = ["wgpu"] }
pyo3.workspace = true
memmap2.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
