[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "dsp-kitchen"
version = "0.1.0"
description = "High-throughput real-time digital signal processing library in Rust for large-scale neuroscience electrophysiology"
readme = "README.md"
authors = [{ name = "jesusdpa1", email = "jesuspenalozaa2@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
]

[tool.maturin]
manifest-path = "dsp_kitchen_py/Cargo.toml"
module-name = "dsp_kitchen_bindings.dsp_kitchen_bindings"
python-source = "dsp_kitchen_py"
features = ["extension-module"]

[tool.ruff]
src = ["dsp_kitchen_py/dsp_kitchen_bindings", "dsp_kitchen_py/dsp_kitchen"]


[dependency-groups]
dev = ["ipykernel>=7.3.0", "ipywidgets>=8.1.9", "ruff>=0.16.9"]
