[package]
name = "dsp-synapse"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dsp-core.workspace = true
dsp-base.workspace = true
dsp-stream.workspace = true
cubecl = { workspace = true, features = ["wgpu"] }
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
