"""
Spikes and units: probes, detection, deduplication, snippet extraction, localization, drift and
kriging, clustering and template matching, quality and response metrics, sorting files,
streaming detection of whole recordings; ``ml`` holds sorters from papers and published
artifacts.
"""

from dsp_kitchen_bindings import (
    DeduplicatedSpike,
    ProbeLayout,
    SortingOutput,
    SpikeEvent,
    StreamingDetectionResult,
    WaveformSnippet,
    cluster_density_peaks,
    cluster_gmm,
    cluster_kde_merge,
    compare_sortings,
    compare_spike_trains,
    compute_amplitude_cutoff,
    compute_autocorrelogram,
    compute_crosscorrelogram,
    compute_d_prime,
    compute_firing_rate,
    compute_isi,
    compute_isolation_distance,
    compute_mep,
    compute_presence_ratio,
    compute_psth,
    compute_silhouette_score,
    compute_snr,
    compute_sta,
    compute_template,
    correct_drift_kriging,
    decompose_hdemg_cbss,
    deduplicate_spikes,
    detect_recording,
    detect_spikes,
    estimate_noise,
    estimate_nonrigid_drift,
    estimate_rigid_drift,
    extract_snippets,
    hdbscan,
    kmeans,
    load_nwb_units,
    load_sorting,
    localize_spikes,
    match_spikes_matching_pursuit,
    save_sorting,
)

from . import ml

__all__ = [
    "ml",
    "DeduplicatedSpike",
    "ProbeLayout",
    "SortingOutput",
    "SpikeEvent",
    "StreamingDetectionResult",
    "WaveformSnippet",
    "cluster_density_peaks",
    "cluster_gmm",
    "cluster_kde_merge",
    "compare_sortings",
    "compare_spike_trains",
    "compute_amplitude_cutoff",
    "compute_autocorrelogram",
    "compute_crosscorrelogram",
    "compute_d_prime",
    "compute_firing_rate",
    "compute_isi",
    "compute_isolation_distance",
    "compute_mep",
    "compute_presence_ratio",
    "compute_psth",
    "compute_silhouette_score",
    "compute_snr",
    "compute_sta",
    "compute_template",
    "correct_drift_kriging",
    "decompose_hdemg_cbss",
    "deduplicate_spikes",
    "detect_recording",
    "detect_spikes",
    "estimate_noise",
    "estimate_nonrigid_drift",
    "estimate_rigid_drift",
    "extract_snippets",
    "hdbscan",
    "kmeans",
    "load_nwb_units",
    "load_sorting",
    "localize_spikes",
    "match_spikes_matching_pursuit",
    "save_sorting",
]
