[package]
name = "dsp-stream"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
quinn.workspace = true
prost.workspace = true
tokio.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
rcgen.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
